### ISSUE TITLE
Does not animate in RN 0.46

### ISSUE THREAD

**Issue by bcifu** [lhandel/react-native-card-flip#1]
The title sort of says it all.  When using React Native 0.46.0, the card flip animation will start and then the card will disappear until the animation is completed and the card is flipped.  If anyone has a work around or a fix, that would be much appreciated.

**Comment by lhandel** [comment]
on android or iOS?

**Comment by bcifu** [comment]
Android, sorry.

**Comment by lhandel** [comment]
Awesome! Yes that would be great!
